default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") { nil } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default

development:
  <<: *default
  database: url_shortener_development

test:
  <<: *default
  url: nil
  database: url_shortener_test
  host: db
  user: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>
